### ISSUE TITLE
cannot run : npm start

### ISSUE THREAD

**Issue by wharsojo** [iiison/tes#1]
Test on Windows 10 & Macbook pro, here is screenshot on windows :  
![image](https://user-images.githubusercontent.com/11621/127307377-9ede0d8a-2b8b-49fb-9415-575cd4ccd35c.png)

**Comment by wharsojo** [comment]
```bash
PS C:\Github\tes> npm start

> Static-Pin-Web-Views@1.0.0 start
> webpack-dev-server --config webpack.config.babel.js --color --progress --hot --inline --mode development

node:internal/modules/cjs/loader:1109
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\Github\tes\webpack.config.babel.js
require() of ES modules is not supported.
require() of C:\Github\tes\webpack.config.babel.js from C:\Github\tes\node_modules\webpack-cli\bin\utils\convert-argv.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename webpack.config.babel.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\Github\tes\package.json.

    at new NodeError (node:internal/errors:329:5)
    at Module._extensions..js (node:internal/modules/cjs/loader:1109:13)
    at Object.newLoader [as .js] (C:\Github\tes\node_modules\pirates\lib\index.js:104:7)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at WEBPACK_OPTIONS (C:\Github\tes\node_modules\webpack-cli\bin\utils\convert-argv.js:114:13)
    at requireConfig (C:\Github\tes\node_modules\webpack-cli\bin\utils\convert-argv.js:116:6)
    at C:\Github\tes\node_modules\webpack-cli\bin\utils\convert-argv.js:123:17 {
  code: 'ERR_REQUIRE_ESM'
}
PS C:\Github\tes>

PS C:\Github\tes> node --version
v15.14.0
```
